service: todoApp

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal
  region: eu-west-2
  memorySize: 128

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: graphql
          method: post
          cors:
            origin: '*'
      - http: 
          path: /
          method: get

package:
  exclude:
    - .git/**
